# Generated by Django 3.0.6 on 2020-05-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0003_auto_20200528_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('-id', 'image'), 'verbose_name_plural': 'Galeria'},
        ),
    ]
