# Generated by Django 3.0.6 on 2020-05-29 10:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0004_auto_20200529_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1280, 300], upload_to='images/'),
        ),
    ]
