# Generated by Django 3.0.6 on 2020-05-29 11:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0005_auto_20200529_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[1280, 960], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[1280, 960], upload_to='users/%Y/%m/%d'),
        ),
    ]
