# Generated by Django 3.0.6 on 2020-05-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0006_auto_20200529_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='nofoto',
            new_name='no_image',
        ),
    ]
