# Generated by Django 3.0.6 on 2020-05-31 07:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0007_auto_20200531_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[1280, 960], upload_to='images/posts/', verbose_name='Zdjęcie główne'),
        ),
    ]
