# Generated by Django 3.0.6 on 2020-05-31 09:18

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0008_auto_20200531_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbook',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Czy rocznik jest archiwalny?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[960, 1280], upload_to='users/%Y/%m/%d'),
        ),
    ]
