# Generated by Django 3.0.6 on 2020-05-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0009_auto_20200531_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='bulding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings_gallery', to='page_ap.BaseObjects'),
        ),
    ]
