# Generated by Django 3.0.6 on 2020-05-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0011_auto_20200531_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='bulding',
            new_name='building',
        ),
    ]
