# Generated by Django 3.0.6 on 2020-05-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0012_auto_20200531_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
    ]
