# Generated by Django 3.0.6 on 2020-06-14 10:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0013_remove_images_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[1280, 960], upload_to='images/')),
                ('role', models.IntegerField(choices=[(0, 'Główny'), (1, 'Patron'), (2, 'Partner medialny'), (3, 'Partner')], verbose_name='Status sponsora')),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
    ]
