# Generated by Django 3.0.6 on 2020-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0014_auto_20200614_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',), 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterModelOptions(
            name='sponsors',
            options={'ordering': ('role',), 'verbose_name_plural': 'Sponsorzy'},
        ),
        migrations.AddField(
            model_name='sponsors',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
