# Generated by Django 3.0.6 on 2020-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0015_auto_20200614_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
