# Generated by Django 3.0.6 on 2020-06-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0016_sponsors_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='title',
        ),
    ]
