# Generated by Django 3.0.6 on 2020-06-15 08:28

from django.db import migrations, models
import django_resized.forms
import page_ap.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0017_remove_sponsors_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_acitvated',
            field=models.BooleanField(default=False, verbose_name='Czy jest aktywowany przez trenera?'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[1280, 960], upload_to='images/', validators=[page_ap.models.file_size]),
        ),
    ]
