# Generated by Django 3.0.6 on 2020-06-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0018_auto_20200615_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_acitvated',
            new_name='is_activated',
        ),
    ]
