# Generated by Django 3.0.6 on 2020-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0019_auto_20200615_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rodo',
            field=models.BooleanField(default=False, verbose_name='Zgoda na wyświetlanie danych osobowych'),
        ),
    ]
