# Generated by Django 3.0.6 on 2020-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0020_profile_rodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_persons',
            field=models.ManyToManyField(related_name='team_persons', to='page_ap.Profile', verbose_name='Sztab drużyny'),
        ),
    ]
