# Generated by Django 3.0.6 on 2020-06-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0021_teams_team_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(verbose_name='Data start')),
                ('data_end', models.DateTimeField(verbose_name='Data koniec')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_place', to='page_ap.BaseBuildings', verbose_name='Nazwa boiska')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_trainings', to='page_ap.Teams', verbose_name='Nazwa drużyny')),
            ],
        ),
    ]
