# Generated by Django 3.0.6 on 2020-06-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0022_trainings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='day_time',
            field=models.CharField(default=1, max_length=32, verbose_name='Dzień i godzina treningu'),
            preserve_default=False,
        ),
    ]
