# Generated by Django 3.0.6 on 2020-06-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0024_auto_20200615_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='date_end',
            field=models.TimeField(verbose_name='Data koniec'),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='date_start',
            field=models.TimeField(verbose_name='Data start'),
        ),
    ]
