# Generated by Django 3.0.6 on 2020-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0025_auto_20200615_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='day_time',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], verbose_name='Dzień treningu'),
        ),
    ]
