# Generated by Django 3.0.6 on 2020-06-22 10:08

from django.db import migrations, models
import django_resized.forms
import page_ap.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0026_auto_20200616_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterField(
            model_name='basebuildings',
            name='photo',
            field=models.ImageField(blank=True, upload_to='buildings/%Y/%m/%d', validators=[page_ap.models.file_size]),
        ),
        migrations.AlterField(
            model_name='baseobjects',
            name='photo',
            field=models.ImageField(blank=True, upload_to='baseobjects/%Y/%m/%d', validators=[page_ap.models.file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[1280, 960], upload_to='images/posts/', validators=[page_ap.models.file_size], verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employe_position',
            field=models.IntegerField(blank=True, choices=[(1, 'Trener'), (2, 'II Trener'), (3, 'Trener bramkarzy'), (4, 'Trener przygotowania fizycznego'), (5, 'Kierownik drużyny'), (6, 'Masażysta'), (7, 'Pracownik administracyjny')], null=True, verbose_name='Tytuł pracownika akademii'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, size=[960, 1280], upload_to='users/%Y/%m/%d', validators=[page_ap.models.file_size]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teams/%Y/%m/%d', validators=[page_ap.models.file_size]),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_persons',
            field=models.ManyToManyField(blank=True, related_name='team_persons', to='page_ap.Profile', verbose_name='Sztab drużyny'),
        ),
    ]
