# Generated by Django 3.0.6 on 2020-06-23 08:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0027_auto_20200622_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('employe_position', 'user__last_name'), 'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employe_position',
            field=models.IntegerField(blank=True, choices=[(1, 'Trener'), (2, 'II Trener'), (3, 'Trener bramkarzy'), (4, 'Trener przygotowania fizycznego'), (5, 'Kierownik drużyny'), (6, 'Masażysta'), (7, 'Pracownik administracyjny'), (8, 'Prezez Akademii Piłarskiej'), (9, 'Skarbnik Akademii Piłarskiej')], null=True, verbose_name='Tytuł pracownika akademii'),
        ),
    ]
