# Generated by Django 3.0.6 on 2020-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0028_auto_20200623_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Treść posta'),
        ),
    ]
