# Generated by Django 3.0.6 on 2020-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0029_auto_20200623_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Załaduj plik')),
                ('title', models.CharField(max_length=40, verbose_name='Tytuł pliku')),
            ],
            options={
                'verbose_name_plural': 'Pliki do pobrania',
                'ordering': ('title',),
            },
        ),
    ]
