# Generated by Django 3.0.6 on 2020-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0030_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Załaduj plik'),
        ),
    ]
