# Generated by Django 3.0.6 on 2020-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0031_auto_20200624_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Załaduj plik'),
        ),
    ]
