# Generated by Django 3.0.6 on 2020-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0032_auto_20200624_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='media/files/', verbose_name='Załaduj plik'),
        ),
    ]
