# Generated by Django 3.0.6 on 2020-06-24 12:18

from django.db import migrations, models
import page_ap.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0033_auto_20200624_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=page_ap.models.user_directory_path, verbose_name='Załaduj plik'),
        ),
    ]
