# Generated by Django 3.0.6 on 2020-06-25 07:05

from django.db import migrations, models
import page_ap.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_ap', '0034_auto_20200624_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=page_ap.models.user_directory_path, validators=[page_ap.models.file_size], verbose_name='Załaduj plik'),
        ),
    ]
