# Generated by Django 3.0.6 on 2020-12-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coach',
            new_name='Coach2',
        ),
    ]
