# Generated by Django 3.1.4 on 2020-12-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20201216_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='year',
            field=models.CharField(max_length=8, verbose_name='Rocznik np: 2008'),
        ),
    ]
