# Generated by Django 3.1.4 on 2020-12-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20201217_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='members',
            name='born_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='members',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.coach2'),
        ),
        migrations.AlterField(
            model_name='members',
            name='declaration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data złażenia deklaracji'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Emial'),
        ),
        migrations.AlterField(
            model_name='members',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='members',
            name='info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='members',
            name='medical_exam',
            field=models.DateField(blank=True, null=True, verbose_name='Badania lekarskie'),
        ),
        migrations.AlterField(
            model_name='members',
            name='parent_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Opiekun'),
        ),
        migrations.AlterField(
            model_name='members',
            name='pesel',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Pesel'),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Kontakt telefoniczny'),
        ),
        migrations.AlterField(
            model_name='members',
            name='year',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Rocznik np: 2008'),
        ),
    ]
