from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from django.views.decorators.cache import cache_page
from .sitemaps import *

sitemaps = {
    'user_update': UserUpdateSiteView,
    'profile': ProfileSiteView,
    'profile_employee': ProfileEmployeesSiteView,
    'my_players': MyPlayersSiteView,
    'profile_players': ProfilePlayersSiteView,
    'post_details': PostSiteView,
    'posts_teams': PostsTeamsSiteView,
    'posts_teams_by_year': PostsTeamsByYearSiteView,
    'teams': TeamsSiteView,
    'teams_by_year': TeamsByYearSiteView,
    'coachs': CoachsSiteView,
    'players': PlayersSiteView,
    'static': StaticViewSiteMap,
    'base_building': BaseBuildingsSiteView,
    'del_training': DeleteTrainingSiteView,
    'update_training': UpdateTrainingSiteView,
}

urlpatterns = [
    path('sitemap.xml',
         sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('', MainView.as_view(), name='main'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('profile_employee_update/<int:pk>',
         ProfileEmployeUpdateView.as_view(),
         name='profile_employee_update'),
    path('profile_player_update/<int:pk>',
         ProfilePlayerUpdateView.as_view(),
         name='profile_player_update'),
    path('aktualnosci/', PostsView.as_view(), name='posts'),
    path('dodaj_aktualnosci/', CreatePostView.as_view(), name='add_post'),
    path('aktualnosci/<slug:slug>/<int:pk>',
         PostDetailView.as_view(),
         name='post_details'),
    path('aktualnosci/druzyny/<slug:slug>/<int:pk>',
         PostsTeamView.as_view(),
         name='posts_team'),
    path('aktualnosci/rocznik/<slug:slug>/<int:pk>',
         PostsTeamByYearView.as_view(),
         name='posts_team_by_year'),
    path('dodaj_galerie_zdjec/<int:pk>',
         CreatePostGalleryView.as_view(),
         name='add_imgaes_post'),
    path('trenerzy/', CoachsView.as_view(), name='coachs'),
    path('trenerzy/<slug:slug>/<int:pk>',
         CoachDetailView.as_view(),
         name='coach_details'),
    path('pilkarze_akademii/lista/<int:pk>',
         My_Players_list_View.as_view(),
         name='my_players_list'),
    path('pilkarze_akademii/<slug:slug>/<int:pk>',
         PlayerDetailView.as_view(),
         name='player_details'),
    path('dodaj_rocznik/', CreateYearBookView.as_view(), name='add_yearbook'),
    path('dodaj_duzyne/', CreateTeamView.as_view(), name='add_team'),
    path('druzyny/', TeamsView.as_view(), name='teams'),
    path('druzyny/<slug:slug>/<int:pk>',
         TeamDetailsView.as_view(),
         name='team_details'),
    path('druzyny/lista/', TeamsListView.as_view(), name='teams_list'),
    path('druzyny/rocznik/<slug:slug>/<int:pk>',
         TeamsByYearView.as_view(),
         name='teams_by_year'),
    path('dodaj_trening/<int:pk>',
         CreateTrainingView.as_view(),
         name='add_training'),
    path('edytuj_trening/<int:pk>',
         UpdateTrainingView.as_view(),
         name='update_training'),
    path('usun_trening/<int:pk>',
         DeleteTrainingView.as_view(),
         name='del_training'),
    path('baza_treningowa/', BuildingsView.as_view(), name='buildings'),
    path('baza_treningowa/<slug:slug>/<int:pk>',
         BuildingDetailsView.as_view(),
         name='building_details'),
    path('kontakt_z_nami', ContactView.as_view(), name='contact'),
    path('zaladuj_plik/', UploadFileView.as_view(), name='upload_file'),
    path('pliki_do_pobrania/', FilesView.as_view(), name='files_list'),
    path('wyslij_wiadomosc/',
         SendingEmailsView.as_view(),
         name='sending_email'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
